-- Audit trail. Append only, hash chained, privacy safe.
-- This is the first Zantrix owned migration. Flyway owns this schema.

create table audit_event (
    id              bigint generated by default as identity primary key,
    recorded_at     timestamptz  not null,
    actor           varchar(255) not null,
    action          varchar(16)  not null,
    entity_type     varchar(255),
    entity_id       varchar(255),
    patient_id      varchar(255),
    outcome         varchar(16)  not null,
    source_ip       varchar(64),
    break_the_glass boolean      not null,
    content_hash    varchar(64)  not null,
    previous_hash   varchar(64)  not null,
    hash            varchar(64)  not null
);

create index idx_audit_event_patient_id on audit_event (patient_id);
create index idx_audit_event_recorded_at on audit_event (recorded_at);

-- Single row holding the hash of the most recent entry. Locked on each write.
create table audit_chain_head (
    id        bigint       primary key,
    last_hash varchar(64)  not null
);

insert into audit_chain_head (id, last_hash) values (1, 'GENESIS');
